const currencyData = {
  USD: { countryCode: "US", name: "Dollar" },
  EUR: { countryCode: "EU", name: "Euro" },
  GBP: { countryCode: "GB", name: "Pound" },
  RUB: { countryCode: "RU", name: "Ruble" },
  KZT: { countryCode: "KZ", name: "Tenge" },
  JPY: { countryCode: "JP", name: "Yen" },
  CNY: { countryCode: "CN", name: "Yuan" },
  CAD: { countryCode: "CA", name: "Canadian Dollar" },
  AUD: { countryCode: "AU", name: "Australian Dollar" },
  CHF: { countryCode: "CH", name: "Swiss Franc" },
  NZD: { countryCode: "NZ", name: "New Zealand Dollar" },
  INR: { countryCode: "IN", name: "Indian Rupee" },
  MXN: { countryCode: "MX", name: "Mexican Peso" },
  BRL: { countryCode: "BR", name: "Brazilian Real" },
  ZAR: { countryCode: "ZA", name: "South African Rand" },
  SGD: { countryCode: "SG", name: "Singapore Dollar" },
  HKD: { countryCode: "HK", name: "Hong Kong Dollar" },
  SEK: { countryCode: "SE", name: "Swedish Krona" },
  NOK: { countryCode: "NO", name: "Norwegian Krone" },
  DKK: { countryCode: "DK", name: "Danish Krone" },
  SAR: { countryCode: "SA", name: "Saudi Riyal" },
  AED: { countryCode: "AE", name: "UAE Dirham" },
  QAR: { countryCode: "QA", name: "Qatari Riyal" },
  THB: { countryCode: "TH", name: "Thai Baht" },
  MYR: { countryCode: "MY", name: "Malaysian Ringgit" },
  IDR: { countryCode: "ID", name: "Indonesian Rupiah" },
  PHP: { countryCode: "PH", name: "Philippine Peso" },
  COP: { countryCode: "CO", name: "Colombian Peso" },
  CLP: { countryCode: "CL", name: "Chilean Peso" },
  ARS: { countryCode: "AR", name: "Argentine Peso" },
  PEN: { countryCode: "PE", name: "Peruvian Sol" },
  UAH: { countryCode: "UA", name: "Ukrainian Hryvnia" },
  PLN: { countryCode: "PL", name: "Polish Zloty" },
  HUF: { countryCode: "HU", name: "Hungarian Forint" },
  CZK: { countryCode: "CZ", name: "Czech Koruna" },
  ISK: { countryCode: "IS", name: "Icelandic Krona" },
  RON: { countryCode: "RO", name: "Romanian Leu" },
  HRK: { countryCode: "HR", name: "Croatian Kuna" },
  BGN: { countryCode: "BG", name: "Bulgarian Lev" },
  TRY: { countryCode: "TR", name: "Turkish Lira" },
};

export default currencyData;
